services:
  frontend:
    build:
      context: ../Frontend
    ports:
      - "5173:5173"
    volumes:
      - ../Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodb_data:/data/db

# example microservice:
#   microservice1:
#     build:
#       context: ./microservices/service1
#     ports:
#       - "4001:4001"
#     depends_on:
#       - mongodb
#     env_file:
#       - .env

volumes:
  mongodb_data:
# frontend: http://localhost:5173
# backend: http://localhost:4000
#mongodb: localhost:27017
